# 2. NumPy 배열

* NumPy에는 **ndarray**라는 데에터 타입의 배열이 사용된다.
* 같은 타입의 데이터만 저장할 수 있다.
* Python list에 비해 계산 속도가 빠르다.

In [2]:
import numpy as np

## 2-1. np.array() 함수로 생성하기

### 1차원 배열 생성하기

In [3]:
# 1차원 배열 생성하기
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (c

In [4]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [5]:
# type확인
type(arr)

numpy.ndarray

In [6]:
# array함수에는 data에 1개만 들어가야함.
np.array(1, 2, 3, 4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [7]:
# 데이터 타입 확인
arr.dtype

dtype('int64')

In [8]:
# overflow 테스트
arr = np.array([2147483647, 2, 3, 4])
arr

array([2147483647,          2,          3,          4])

In [9]:
# overflow 테스트
arr = np.array([21474836478, 2, 3, 4])
arr

array([21474836478,           2,           3,           4])

In [10]:
# overflow 테스트
arr = np.array([21474836478, 2, 3, 4], dtype=np.int32)
arr

array([-2,  2,  3,  4], dtype=int32)

In [11]:
arr = np.array([1, 2, 3, 4], dtype=float)
arr

array([1., 2., 3., 4.])

In [12]:
arr.dtype

dtype('float64')

In [13]:
# shape : 각 차원의 배열의 size(차원의 모양)
arr.shape

(4,)

In [14]:
# size : 배열 전체의 요소의 개수
arr.size

4

In [15]:
# ndim : 차원의 수
arr.ndim

1

In [16]:
# ndarray에는 같은 데이터만 들어가야 함
arr = np.array([1, 2, 3, 3.14])
arr

array([1.  , 2.  , 3.  , 3.14])

In [17]:
arr = np.array([1, 2, 3, 3.14], dtype=int)
arr

array([1, 2, 3, 3])

In [26]:
# int, float, string -> string
# >(big-endian), <(little-endian)
# 32-character string
arr = np.array([1, 3.14, '1234'])
arr

array(['1', '3.14', '1234'], dtype='<U32')

In [27]:
arr = np.array([1, 3.14, '123456789012345678901234567890123'])
arr

array(['1', '3.14', '123456789012345678901234567890123'], dtype='<U33')

In [28]:
new_arr = arr.astype(float)
new_arr

array([1.00000000e+00, 3.14000000e+00, 1.23456789e+32])