# 2. NumPy 배열

* NumPy에는 **ndarray**라는 데에터 타입의 배열이 사용된다.
* 같은 타입의 데이터만 저장할 수 있다.
* Python list에 비해 계산 속도가 빠르다.

In [1]:
import numpy as np

## 2-1. np.array() 함수로 생성하기

### 1차원 배열 생성하기

In [2]:
# 1차원 배열 생성하기
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (c

In [3]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [4]:
# type확인
type(arr)

numpy.ndarray

In [5]:
# array함수에는 data에 1개만 들어가야함.
# np.array(1, 2, 3, 4) error

In [6]:
# 데이터 타입 확인
arr.dtype

dtype('int64')

In [7]:
# overflow 테스트
arr = np.array([2147483647, 2, 3, 4])
arr

array([2147483647,          2,          3,          4])

In [8]:
# overflow 테스트
arr = np.array([21474836478, 2, 3, 4])
arr

array([21474836478,           2,           3,           4])

In [9]:
# overflow 테스트
arr = np.array([21474836478, 2, 3, 4], dtype=np.int32)
arr

array([-2,  2,  3,  4], dtype=int32)

In [10]:
arr = np.array([1, 2, 3, 4], dtype=float)
arr

array([1., 2., 3., 4.])

In [11]:
arr.dtype

dtype('float64')

In [12]:
# shape : 각 차원의 배열의 size(차원의 모양)
arr.shape

(4,)

In [13]:
# size : 배열 전체의 요소의 개수
arr.size

4

In [14]:
# ndim : 차원의 수
arr.ndim

1

In [15]:
# ndarray에는 같은 데이터만 들어가야 함
arr = np.array([1, 2, 3, 3.14])
arr

array([1.  , 2.  , 3.  , 3.14])

In [16]:
arr = np.array([1, 2, 3, 3.14], dtype=int)
arr

array([1, 2, 3, 3])

In [17]:
# int, float, string -> string
# >(big-endian), <(little-endian)
# 32-character string
arr = np.array([1, 3.14, '1234'])
arr

array(['1', '3.14', '1234'], dtype='<U32')

In [18]:
arr = np.array([1, 3.14, '123456789012345678901234567890123'])
arr

array(['1', '3.14', '123456789012345678901234567890123'], dtype='<U33')

In [19]:
new_arr = arr.astype(float)
new_arr

array([1.00000000e+00, 3.14000000e+00, 1.23456789e+32])

### 2차원 배열 생성하기

In [27]:
arr2 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
type(arr2)

numpy.ndarray

In [28]:
arr2.dtype, arr2.shape, arr2.size, arr2.ndim

(dtype('int64'), (3, 4), 12, 2)

In [23]:
new_arr2 = arr2.astype(int)
new_arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 2-2. np.arange() 함수로 생성하기

### 1차원 배열 생성하기

In [29]:
for i in range(5):  # 0 ~ 4
    print(i)

0
1
2
3
4


In [30]:
for i in range(1, 11, 2):  # 1, 3, 5, 7, 9
    print(i)

1
3
5
7
9


In [33]:
arr = np.arange(1, 11)  # 1~10
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

In [35]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : integer or real
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : integer or real, optional
    Spacing between values.  For any output `out`, this is the distance
  

In [37]:
np.arange(start=1, stop=11, step=2)

array([1, 3, 5, 7, 9])

### 2차원 배열 생성하기

In [38]:
arr = np.arange(12)  # 0, 11
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
arr.reshape(3, 4), arr.reshape(4, 3)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [43]:
new_arr = arr.reshape(3, 4)  # shape
new_arr, arr

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))

In [44]:
arr.reshape((3, 4))  # 정확한 형태로 쓰려면 tuple

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

총 개수가 작거나 크면 에러가 뜬다  
원본 데이터와는 관련 없이 새로운 데이터를 만든다

In [45]:
new_arr = arr.reshape((3, 3))
new_arr

ValueError: cannot reshape array of size 12 into shape (3,3)

In [46]:
new_arr = arr.reshape((3, 5))
new_arr

ValueError: cannot reshape array of size 12 into shape (3,5)

원본을 바꾸려면 아래와 같이 한다

In [47]:
arr.shape = (3, 4)

In [48]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 2-3. np.zeros() 함수로 생성

In [52]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [53]:
arr = np.zeros(5, dtype=int)
arr

array([0, 0, 0, 0, 0])

In [54]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. note::
        The ``like`` keyword is an experimental feature pending on
        acceptance of :ref:`NEP 35 <NEP35>`.

    .. ve

In [56]:
arr2 = np.zeros((3, 4), dtype=int)
arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## 2-4. np.ones() 함수로 생성

In [57]:
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [58]:
arr2 = np.ones((3, 4), dtype=int)
arr2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## 2-5. np.linspace() 함수로 생성

In [59]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is Fals

In [61]:
arr = np.linspace(0, 10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [66]:
arr = np.linspace(0, 10)
arr

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [67]:
arr.shape

(50,)

In [68]:
arr2 = arr.reshape((5, 10))
arr2

array([[ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469],
       [ 2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
         3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102],
       [ 4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
         5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735],
       [ 6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
         7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367],
       [ 8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
         9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]])

## 2-6. np.full() 함수로 생성

In [72]:
np.full((4, 2), 4)

array([[4, 4],
       [4, 4],
       [4, 4],
       [4, 4]])

In [73]:
np.full?

Signature: np.full(shape, fill_value, dtype=None, order='C', *, like=None)
Docstring:
Return a new array of given shape and type, filled with `fill_value`.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
fill_value : scalar or array_like
    Fill value.
dtype : data-type, optional
    The desired data-type for the array  The default, None, means
     `np.array(fill_value).dtype`.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. note::
        The ``like`` keyword is an experimental feature 

In [74]:
arr = np.full((4,), 10)
arr

array([10, 10, 10, 10])

## 2-7. np.eye() 함수로 생성

In [75]:
# 단위 행렬, 항등 행렬
np.eye?

Signature: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array o

In [76]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 2-8. np.random으로 생성

In [77]:
np.random.rand(10)

array([0.26458549, 0.8958493 , 0.13782237, 0.60779691, 0.50776733,
       0.04333602, 0.01090969, 0.66093036, 0.68637483, 0.02986311])

In [78]:
np.random.rand?

Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      builtin_function_or_method


In [84]:
np.random.rand(5, 3, 2)

array([[[0.60685578, 0.19639632],
        [0.03041053, 0.91261083],
        [0.14699354, 0.75229835]],

       [[0.33742134, 0.40358525],
        [0.49913156, 0.60557388],
        [0.15909256, 0.52414051]],

       [[0.07393858, 0.93781386],
        [0.49845581, 0.43691281],
        [0.09673998, 0.24897368]],

       [[0.63447857, 0.23794998],
        [0.85203816, 0.44103375],
        [0.59005011, 0.0076462 ]],

       [[0.4149509 , 0.71067359],
        [0.84939888, 0.36732872],
        [0.18935381, 0.33013322]]])

In [89]:
arr = np.random.randint(0, 4, (2, 4))
arr

array([[2, 3, 3, 3],
       [0, 3, 1, 0]])

In [107]:
np.random.seed(123)
np.random.rand(2, 3)

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

In [113]:
np.random.rand(2, 3)

array([[0.42635131, 0.89338916, 0.94416002],
       [0.50183668, 0.62395295, 0.1156184 ]])

## 2-9. Numpy 배열 Save & Load

In [2]:
arr = np.arange(0, 5)  # 0~4
arr

array([0, 1, 2, 3, 4])

In [3]:
np.save?

Signature: np.save(file, arr, allow_pickle=True, fix_imports=True)
Docstring:
Save an array to a binary file in NumPy ``.npy`` format.

Parameters
----------
file : file, str, or pathlib.Path
    File or filename to which the data is saved.  If file is a file-object,
    then the filename is unchanged.  If file is a string or Path, a ``.npy``
    extension will be appended to the filename if it does not already
    have one.
arr : array_like
    Array data to be saved.
allow_pickle : bool, optional
    Allow saving object arrays using Python pickles. Reasons for disallowing
    pickles include security (loading pickled data can execute arbitrary
    code) and portability (pickled objects may not be loadable on different
    Python installations, for example if the stored objects require libraries
    that are not available, and not all pickled data is compatible between
    Python 2 and Python 3).
    Default: True
fix_imports : bool, optional
    Only useful in forcing objects in obje

In [4]:
np.save('my_arr', arr)

In [7]:
np.load?

Signature:
np.load(
    file,
    mmap_mode=None,
    allow_pickle=False,
    fix_imports=True,
    encoding='ASCII',
)
Docstring:
Load arrays or pickled objects from ``.npy``, ``.npz`` or pickled files.

.. warning:: Loading files that contain object arrays uses the ``pickle``
             module, which is not secure against erroneous or maliciously
             constructed data. Consider passing ``allow_pickle=False`` to
             load data that is known not to contain object arrays for the
             safer handling of untrusted sources.

Parameters
----------
file : file-like object, string, or pathlib.Path
    The file to read. File-like objects must support the
    ``seek()`` and ``read()`` methods. Pickled files require that the
    file-like object support the ``readline()`` method as well.
mmap_mode : {None, 'r+', 'r', 'w+', 'c'}, optional
    If not None, then memory-map the file, using the given mode (see
    `numpy.memmap` for a detailed description of the modes).  A
  

In [8]:
new_arr = np.load('my_arr.npy')
new_arr

array([0, 1, 2, 3, 4])