In [1]:
import numpy as np

# 3. 연산

## 3-1. 산술연산

In [2]:
# 1차원 배열
a = np.arange(1, 5)  # 1~4
b = np.arange(5, 9)  # 5~8

In [3]:
a, b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [4]:
# shape이 같아야 함
a + b

array([ 6,  8, 10, 12])

In [5]:
a - b

array([-4, -4, -4, -4])

In [6]:
a * b

array([ 5, 12, 21, 32])

In [7]:
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [8]:
# 2차원 배열
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)

In [9]:
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [10]:
a + b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [11]:
a - b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [12]:
# 단순 곱셈 (이렇게는 안 쓰임)
a * b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [13]:
a / b

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

### 행렬의 곱셈 (dot product)

In [14]:
b = np.arange(7, 13).reshape(3, 2)

In [15]:
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]]))

In [16]:
np.dot(a, b)

array([[ 58,  64],
       [139, 154]])

In [17]:
1*7 + 2*9 + 3*11

58

In [18]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

### 배열과 스칼라(숫자)와의 연산 (Broadcasting)

In [19]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [20]:
a + 3

array([4, 5, 6])

In [21]:
a - 3

array([-2, -1,  0])

In [22]:
a * 3

array([3, 6, 9])

In [23]:
a / 3

array([0.33333333, 0.66666667, 1.        ])

## 3-2. Aggregation 함수

### 1차원 함수

In [24]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [25]:
# max값 찾기
np.max(a)

5

In [26]:
np.min(a)

1

In [27]:
# sum값 구하기
np.sum(a)

15

In [28]:
# 평균값 구하기
np.mean(a)

3.0

In [29]:
a.min(), a.max(), a.mean()

(1, 5, 3.0)

In [30]:
# 이상치(outlier)가 있는 경우 평균값이 요 배열의 데이터를 잘 대표한다고 볼 수 있을까?
b = np.array([1, 2, 3, 4, 100])
b

array([  1,   2,   3,   4, 100])

In [31]:
# 중앙값(median), 중위값
np.median(b)

3.0

In [32]:
np.median(np.array([1, 2, 100, 4, 3]))

3.0

In [33]:
# 데이터가 짝수개인 경우
b = np.array([1, 3, 5, 100])
np.median(b)

4.0

In [34]:
# 표준편차 (standard deviation)
np.std(a)

1.4142135623730951

In [35]:
np.sqrt(np.mean((a - a.mean()) ** 2))

1.4142135623730951

### 2차원 배열

In [36]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
np.max(a), a.max(), np.min(a), a.min()

(6, 6, 1, 1)

In [38]:
# 2차원 배열의 경우 axis를 주어 각 행과 열의 max값을 구할 수 있음
np.max(a, axis=0)  # 행(row)

array([4, 5, 6])

In [39]:
np.max(a, axis=1)

array([3, 6])

In [40]:
np.min(a, axis=0), np.min(a, axis=1)

(array([1, 2, 3]), array([1, 4]))

In [41]:
np.sum(a), np.sum(a, axis=0), np.sum(a, axis=1)

(21, array([5, 7, 9]), array([ 6, 15]))

In [42]:
# cumsum, corrcoef(상관계수 구하기)
a = np.array([1, 2, 3, 4, 5])
np.cumsum(a)


array([ 1,  3,  6, 10, 15])

In [43]:
b = np.arange(1, 7).reshape(2, 3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
np.cumsum(b)

array([ 1,  3,  6, 10, 15, 21])

In [45]:
np.cumsum(b, axis=0)

array([[1, 2, 3],
       [5, 7, 9]])

In [46]:
# corrcoef (상관계수)
# 키와 몸무게의 상관관계
h = [160, 165, 170, 180]
w = [47, 55, 70, 85]
np.corrcoef(h, w)

array([[1.        , 0.99040485],
       [0.99040485, 1.        ]])

In [47]:
ha = np.mean(h)
wa = np.mean(w)
ha, wa

(168.75, 64.25)

In [48]:
a = np.sqrt(np.sum((h - ha) ** 2))
a

14.79019945774904

In [49]:
b = np.sqrt(np.sum((w - wa) ** 2))
b

29.098969053902923

In [50]:
c = np.sum((h - ha) * (w - wa))
c

426.25

In [51]:
r = c / (a * b)
r

0.990404850180661

## 비교 (Comparison)

In [52]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [53]:
a >= 3

array([False, False,  True,  True,  True])

In [54]:
a + 3

array([4, 5, 6, 7, 8])

In [55]:
a == 3

array([False, False,  True, False, False])