# 3. 연산

In [55]:
import numpy as np

In [56]:
# 1차원 배열
a = np.arange(1, 5)  # 1~4
b = np.arange(5, 9)  # 5~8

In [57]:
a, b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [58]:
# shape이 같아야 함
a + b

array([ 6,  8, 10, 12])

In [59]:
a - b

array([-4, -4, -4, -4])

In [60]:
a * b

array([ 5, 12, 21, 32])

In [61]:
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [62]:
# 2차원 배열
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)

In [63]:
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [64]:
a + b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [65]:
a - b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [66]:
# 단순 곱셈 (이렇게는 안 쓰임)
a * b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [67]:
a / b

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

## 행렬의 곱셈 (dot product)

In [68]:
b = np.arange(7, 13).reshape(3, 2)

In [69]:
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]]))

In [70]:
np.dot(a, b)

array([[ 58,  64],
       [139, 154]])

In [71]:
1*7 + 2*9 + 3*11

58

In [72]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

## 배열과 스칼라(숫자)와의 연산 (Broadcasting)

In [73]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [74]:
a + 3

array([4, 5, 6])

In [75]:
a - 3

array([-2, -1,  0])

In [76]:
a * 3

array([3, 6, 9])

In [77]:
a / 3

array([0.33333333, 0.66666667, 1.        ])

## 3-2. Aggregation 함수

### 1차원 함수

In [78]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [79]:
# max값 찾기
np.max(a)

5

In [80]:
np.min(a)

1

In [81]:
# sum값 구하기
np.sum(a)

15

In [82]:
# 평균값 구하기
np.mean(a)

3.0

In [83]:
a.min(), a.max(), a.mean()

(1, 5, 3.0)

In [84]:
# 이상치(outlier)가 있는 경우 평균값이 요 배열의 데이터를 잘 대표한다고 볼 수 있을까?
b = np.array([1, 2, 3, 4, 100])
b

array([  1,   2,   3,   4, 100])

In [85]:
# 중앙값(median), 중위값
np.median(b)

3.0

In [86]:
np.median(np.array([1, 2, 100, 4, 3]))

3.0

In [87]:
# 데이터가 짝수개인 경우
b = np.array([1, 3, 5, 100])
np.median(b)

4.0

In [88]:
# 표준편차 (standard deviation)
np.std(a)

1.4142135623730951

In [89]:
np.sqrt(np.mean((a - a.mean()) ** 2))

1.4142135623730951

### 2차원 배열

In [90]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
np.max(a), a.max(), np.min(a), a.min()

(6, 6, 1, 1)

In [92]:
# 2차원 배열의 경우 axis를 주어 각 행과 열의 max값을 구할 수 있음
np.max(a, axis=0)  # 행(row)

array([4, 5, 6])

In [93]:
np.max(a, axis=1)

array([3, 6])

In [94]:
np.min(a, axis=0), np.min(a, axis=1)

(array([1, 2, 3]), array([1, 4]))

In [95]:
np.sum(a), np.sum(a, axis=0), np.sum(a, axis=1)

(21, array([5, 7, 9]), array([ 6, 15]))

In [96]:
# cumsum, corrcoef(상관계수 구하기)

## 비교 (Comparison)

In [97]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [99]:
a >= 3

array([False, False,  True,  True,  True])

In [100]:
a + 3

array([4, 5, 6, 7, 8])

In [101]:
a == 3

array([False, False,  True, False, False])