# 3. 연산

In [1]:
import numpy as np

In [2]:
# 1차원 배열
a = np.arange(1, 5)  # 1~4
b = np.arange(5, 9)  # 5~8

In [3]:
a, b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [4]:
# shape이 같아야 함
a + b

array([ 6,  8, 10, 12])

In [5]:
a - b

array([-4, -4, -4, -4])

In [6]:
a * b

array([ 5, 12, 21, 32])

In [7]:
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [9]:
# 2차원 배열
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)

In [10]:
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [12]:
a + b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [13]:
a - b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [14]:
# 단순 곱셈 (이렇게는 안 쓰임)
a * b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [15]:
a / b

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

## 행렬의 곱셈 (dot product)

In [16]:
b = np.arange(7, 13).reshape(3, 2)

In [17]:
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]]))

In [18]:
np.dot(a, b)

array([[ 58,  64],
       [139, 154]])

In [19]:
1*7 + 2*9 + 3*11

58

In [20]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

## 배열과 스칼라(숫자)와의 연산 (Broadcasting)

In [21]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [22]:
a + 3

array([4, 5, 6])

In [23]:
a - 3

array([-2, -1,  0])

In [24]:
a * 3

array([3, 6, 9])

In [25]:
a / 3

array([0.33333333, 0.66666667, 1.        ])

## 3-2. aggregation