In [5]:
import numpy as np

# 4. 정렬

## 4-1. 1차원 배열

In [6]:
np.random.seed(100)
arr = np.random.randint(1, 10, size=10)  # 1~9, 10개
arr

array([9, 9, 4, 8, 8, 1, 5, 3, 6, 3])

In [7]:
np.sort(arr)

array([1, 3, 3, 4, 5, 6, 8, 8, 9, 9])

In [8]:
np.sort(arr)[::-1]

array([9, 9, 8, 8, 6, 5, 4, 3, 3, 1])

In [9]:
arr  # 그대로 유지가 됨

array([9, 9, 4, 8, 8, 1, 5, 3, 6, 3])

In [10]:
# 정렬 시 주의사항
np.max(arr)
arr.max()  # -> same

np.sort(arr)  # copied array

array([1, 3, 3, 4, 5, 6, 8, 8, 9, 9])

In [11]:
arr.sort()  # in-place

In [12]:
arr

array([1, 3, 3, 4, 5, 6, 8, 8, 9, 9])

## 4-2. 2차원 배열

In [66]:
np.random.seed(100)
arr2 = np.random.randint(1, 10, size=(3, 4))  # 1~9, size=(3, 4)
arr2

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3]])

In [67]:
np.sort(arr2)  # 행 기준으로 소트가 됨

array([[4, 8, 9, 9],
       [1, 3, 5, 8],
       [3, 3, 3, 6]])

In [69]:
np.sort(arr2, axis=1)  # 사실은 -1이 디폴트

array([[4, 8, 9, 9],
       [1, 3, 5, 8],
       [3, 3, 3, 6]])

In [72]:
np.sort(arr2, axis=0)

array([[6, 1, 3, 3],
       [8, 3, 4, 3],
       [9, 9, 5, 8]])

In [73]:
arr2  # 원본배열 영향X

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3]])

In [74]:
# index를 반환하는 argsort
np.argsort(arr2)

array([[2, 3, 0, 1],
       [1, 3, 2, 0],
       [1, 2, 3, 0]])

In [75]:
np.argsort(arr2, axis=0)

array([[2, 1, 2, 1],
       [1, 2, 0, 2],
       [0, 0, 1, 0]])