# 5. 인덱싱과 슬라이싱

## 5-1. 인덱싱

In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 11)  # 0~9
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[0], arr[4], arr[-1]

(1, 5, 10)

In [4]:
arr2 = np.arange(1, 13).reshape(3, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr2[0][1], arr2[1][2], arr2[2][3]

(2, 7, 12)

In [6]:
arr2[0, 1], arr2[1, 2], arr2[2, 3]  # numpy에서는 다차원 indexing

(2, 7, 12)

In [17]:
arr2[-1][-2], arr2[-1, -2]

(11, 11)

## 5-2. 슬라이싱

### 1차원 배열

In [8]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# 3~끝까지 슬라이싱 ([start:end:step])
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[2:5]

array([3, 4, 5])

In [11]:
# 처음~5 까지 슬라이싱
arr[:5]

array([1, 2, 3, 4, 5])

In [12]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# 슬라이싱을 한후에 값을 변경하면 원본에 영향을 미칠까?
new_arr = arr[:5]
new_arr

array([1, 2, 3, 4, 5])

In [15]:
new_arr[0] = 100

In [16]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [18]:
copy_arr = np.copy(arr)
copy_arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

### 2차원 배열