# 5. 인덱싱과 슬라이싱

## 5-1. 인덱싱

In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 11)  # 0~9
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[0], arr[4], arr[-1]

(1, 5, 10)

In [4]:
arr2 = np.arange(1, 13).reshape(3, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr2[0][1], arr2[1][2], arr2[2][3]

(2, 7, 12)

In [6]:
arr2[0, 1], arr2[1, 2], arr2[2, 3]  # numpy에서는 다차원 indexing

(2, 7, 12)

In [17]:
arr2[-1][-2], arr2[-1, -2]

(11, 11)

## 5-2. 슬라이싱

### 1차원 배열

In [8]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# 3~끝까지 슬라이싱 ([start:end:step])
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[2:5]

array([3, 4, 5])

In [11]:
# 처음~5 까지 슬라이싱
arr[:5]

array([1, 2, 3, 4, 5])

In [12]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# 슬라이싱을 한후에 값을 변경하면 원본에 영향을 미칠까?
new_arr = arr[:5]
new_arr

array([1, 2, 3, 4, 5])

In [15]:
new_arr[0] = 100

In [16]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [18]:
copy_arr = np.copy(arr)
copy_arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

### 2차원 배열

In [19]:
arr2 = np.arange(1, 13).reshape(3, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
# 첫번째 행을 모두 가져오기
arr2[0, :]

array([1, 2, 3, 4])

In [29]:
# 세번째 열을 모두 가져오기
arr2[:, 2]

array([ 3,  7, 11])

In [50]:
# 첫번째, 두번째 행을 모두 가져오기
arr2[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
# 두번째, 세번째 열을 모두 가져오기
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [40]:
# [[2, 3],
#   [6, 7]] 가져오기
arr2[:2, 1:3]

array([[2, 3],
       [6, 7]])

## 5-3. Fancy 인덱싱(공상, 원하다)

### 1차원 배열

In [41]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [42]:
# 1, 3, 5로 된 배열을 만들기
np.array([arr[0], arr[2], arr[4]])

array([100,   3,   5])

In [43]:
# 슬라이싱 [start:end:step]
arr[:5:2]

array([100,   3,   5])

In [44]:
# fancy 인덱싱 (인덱스로 된 배열로 추출)
# arr[0, 2, 4] = arr[0][2][4]
arr[[0, 2, 4]]

array([100,   3,   5])

### 2차원 배열

In [45]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
# [[1, 2, 3, 4],
#  [9, 10, 11, 12]]
np.array([arr2[0], arr2[2]])

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [51]:
# Fancy 인덱싱
arr2[[0, 2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [52]:
# 주의
arr2[0, 2]  # arr2[0][2]

3

In [65]:
# 슬라이싱
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [66]:
# Fancy 인덱싱
arr2[:, [1, 2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

## 5-4. Boolean 인덱싱

In [83]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [84]:
cond = [False, True, False, False, True]
arr[cond]

array([1, 4])

In [85]:
arr[[False, True, False, False, True]]

array([1, 4])

In [86]:
arr > 2

array([False, False, False,  True,  True])

In [87]:
arr[arr > 2]

array([3, 4])

In [88]:
# 짝수만 뽑기
arr[arr % 2 == 0]

array([0, 2, 4])

In [93]:
# 0, 3, 4
arr[(arr < 1) | (arr > 2)]

array([0, 3, 4])

In [95]:
# 2, 3
arr[(arr > 1) & (arr < 4)]

array([2, 3])